# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FirebaseUnrealWrapper' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseUnrealWrapper
	pod 'Firebase/Analytics', '7.5.0'
	pod 'Firebase/Messaging', '7.5.0'
end
